export {default as AddPaymentPage} from "./AddPayment"
export {default as OrderHistory} from "./OrderHistory"
export {default as OrderDetails} from "./OrderDetail"
export {default as PaymentPage} from "./Payments"
export {default as View} from "./View"
export {default as Edit} from "./Edit"
